services:
  mariadb: 
    image: bitnami/mariadb:11.1.5
    restart: unless-stopped
    volumes: 
      - mariadb-glpi-volume:/var/lib/mysql:rw
    env_file: ./.env 
    expose: 
      - "3306"

  mariadb-timezone: 
    image: bitnami/mariadb:11.1.5
    restart: on-failure
    env_file: ./.env
    depends_on:
      - mariadb
    command: mariadb -h $MARIADB_HOST -u root -p$MARIADB_ROOT_PASSWORD -e "GRANT SELECT ON \`mysql\`.\`time_zone_name\` TO 'glpi'@'%'; FLUSH PRIVILEGES;"

  glpi-db-install:
    image: registry.cn-beijing.aliyuncs.com/ourimages/docker-glpi:php-8.3.8-fpm-alpine3.20
    restart: on-failure 
    env_file: ./.env
    volumes: 
      - glpi-marketplace:/var/www/html/marketplace:rw
      - glpi-files:/var/lib/glpi:rw
      - glpi-etc:/etc/glpi:rw    
    depends_on: 
      - mariadb
    command: 
      - /usr/local/bin/glpi-db-install.sh

  glpi-verify-dir: 
    image: registry.cn-beijing.aliyuncs.com/ourimages/docker-glpi:php-8.3.8-fpm-alpine3.20
    restart: on-failure
    volumes: 
      - glpi-marketplace:/var/www/html/marketplace:rw
      - glpi-files:/var/lib/glpi:rw
      - glpi-etc:/etc/glpi:rw
    env_file: ./.env
    depends_on: 
      - glpi-db-install
    command: 
      - /usr/local/bin/glpi-verify-dir.sh

  glpi-db-configure: 
    image: registry.cn-beijing.aliyuncs.com/ourimages/docker-glpi:php-8.3.8-fpm-alpine3.20
    restart: on-failure
    volumes: 
      - glpi-marketplace:/var/www/html/marketplace:rw
      - glpi-files:/var/lib/glpi:rw
      - glpi-etc:/etc/glpi:rw
    env_file: ./.env
    depends_on: 
      - glpi-verify-dir
    command: 
      - /usr/local/bin/glpi-db-configure.sh

  php: 
    image: registry.cn-beijing.aliyuncs.com/ourimages/docker-glpi:php-8.3.8-fpm-alpine3.20
    restart: unless-stopped
    volumes: 
      - glpi-marketplace:/var/www/html/marketplace:rw
      - glpi-files:/var/lib/glpi:rw
      - glpi-etc:/etc/glpi:rw
    env_file: ./.env
    depends_on: 
      - mariadb
      - glpi-db-install
      - glpi-db-configure
      - glpi-verify-dir
    expose: 
      - "9000"

  nginx: 
    image: eftechcombr/glpi:nginx-10.0.16
    restart: unless-stopped
    ports: 
      - "8080:80"
    depends_on: 
      - php

volumes: 
  glpi-marketplace:
  glpi-files:
  glpi-etc:
  glpi-install:
  mariadb-glpi-volume: 

# networks: 
#   glpi-frontend: 
#   glpi-backend:
